name: Build and Deploy
on:
  push:
    branches:
      - production # The branch the action should start when pushed to.
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Prevents overlap if there are multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '17.6.0'
          cache: npm

      - name: Install Node Modules
        run: npm i

      - name: Build ğŸ”§
        run: npm run build

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
